version: "3.7"

services:
  frontend:
    image: node:lts-alpine
    volumes:
      - ./insecurity/frontend:/opt/app
      - /opt/app/node_modules
    working_dir: /opt/app
    environment:
      API_BASE: http://backend:8080/
    restart: on-failure
    stdin_open: true
    ports:
      - "3000:3000"
    command: >
      sh -c "yarn install && yarn start"
  
  backend:
    image: adoptopenjdk/openjdk11:alpine
    command: ./gradlew bootRun
    working_dir: /opt/app
    volumes:
      - ./insecurity/backend:/opt/app
      - /root/.gradle
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: on-failure

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: insecurity
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

